### ISSUE TITLE
Release 1.1.1 breaks angular injection of provider

### ISSUE THREAD

**Issue by jskrzypek** [js-data/js-data-firebase#10]
Check out this codepen: http://codepen.io/jskrzypek/pen/wBLBpZ

All I did was copy wholesale the `.js` & `.html` files from the `angular-firebase` example in the examples folder and bumped the version of the `js-data-firebase` script that it was fetching to `1.1.1`. You can try downgrading it to `1.1.0` again and the adapter will work again. 

I believe the `DSFirebaseAdapterProvider` is not being registered with angular, since in the project I was working it angular couldn't find it.

**Comment by jmdobry** [comment]
Oops, I forgot to create the release for 1.1.1 in Github, so there was no file at `https://github.com/js-data/js-data-firebase/releases/download/1.1.1/js-data-firebase.min.js`. It's there now, so it should work.
