### ISSUE TITLE
Remove "/" prefix on ids

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data-firebase#14]
Make it an option to have the prefix removed, then make the breaking change that removes it for everybody.

**Comment by gdeividas** [comment]
+ 1

**Comment by MatthewOverall** [comment]
In V3 the leading / has been removed.

**Comment by jmdobry** [comment]
This will be quite the breaking change, people will have to migrate their data.

**Comment by jmdobry** [comment]
Fixed in 3.x
