### ISSUE TITLE
Unknown provider: DSFirebaseAdapterProvider

### ISSUE THREAD

**Issue by samuelcastro** [js-data/js-data-firebase#21]
I'm getting this issue when trying to use the DSFirebaseProvider:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:unpr] Unknown provider: DSFirebaseAdapterProvider
```
Usage:
```
'use strict';

adapter.$inject = ['DSFirebaseAdapterProvider'];

export default function adapter(DSFirebaseAdapterProvider) {
  DSFirebaseAdapterProvider.defaults.basePath = 'https://my-firebase.firebaseio.com';
}
```

**Comment by jmdobry** [comment]
You didn't provide enough context for me to help. Can you please fork this plunker and use it to reproduce the issue? http://plnkr.co/edit/RzS7ot?p=info

**Comment by samuelcastro** [comment]
Ok I'll try, I'm setting it with webpack + es6, probably I doing something wrong.

**Comment by jmdobry** [comment]
Then posting your webpack config and the code where you import js-data/js-data-angular/js-data-firebase would be a good start.

**Comment by samuelcastro** [comment]
I've just added the webpack config and the entry app.js file:

http://plnkr.co/edit/f6bj0BKxrewOkHqDMxit?p=preview

**Comment by jmdobry** [comment]
I think because of webpack, js-data-angular can't find js-data-firebase, so it's failing to register the provider for you. So add the following before your first `.config`

```
.provider('DSFirebaseAdapter', function () {
  this.defaults = {}
  this.$get = () => new jsDataFirebase(this.defaults)
})
```

and the rest of your code should work

**Comment by samuelcastro** [comment]
Worked like a charm!

Thank you @jmdobry
