### ISSUE TITLE
Add compatibility with firebase-admin?

### ISSUE THREAD

**Issue by IniZio** [js-data/js-data-firebase#38]
Firebase separates into firebase and firebase-admin package instead of the old all-in-one package. I made a dirty patch to make it work with firebase-admin only in https://github.com/IniZio/js-data-firebase-admin/tree/firebase-admin.

**Comment by crobinson42** [comment]
@IniZio if you want to submit a PR to open the discussion for implementation details I'd be happy to work with you on it.
